Document: python-kafka
Title: Debian python-kafka Manual
Author: <insert document author here>
Abstract: This manual describes what python-kafka is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/python-kafka/python-kafka.sgml.gz

Format: postscript
Files: /usr/share/doc/python-kafka/python-kafka.ps.gz

Format: text
Files: /usr/share/doc/python-kafka/python-kafka.text.gz

Format: HTML
Index: /usr/share/doc/python-kafka/html/index.html
Files: /usr/share/doc/python-kafka/html/*.html
