Document: python-sseclient
Title: Debian python-sseclient Manual
Author: <insert document author here>
Abstract: This manual describes what python-sseclient is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/python-sseclient/python-sseclient.sgml.gz

Format: postscript
Files: /usr/share/doc/python-sseclient/python-sseclient.ps.gz

Format: text
Files: /usr/share/doc/python-sseclient/python-sseclient.text.gz

Format: HTML
Index: /usr/share/doc/python-sseclient/html/index.html
Files: /usr/share/doc/python-sseclient/html/*.html
