Document: kafka
Title: Debian kafka Manual
Author: <insert document author here>
Abstract: This manual describes what kafka is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/kafka/kafka.sgml.gz

Format: postscript
Files: /usr/share/doc/kafka/kafka.ps.gz

Format: text
Files: /usr/share/doc/kafka/kafka.text.gz

Format: HTML
Index: /usr/share/doc/kafka/html/index.html
Files: /usr/share/doc/kafka/html/*.html
