Document: python-pyangbind
Title: Debian python-pyangbind Manual
Author: <insert document author here>
Abstract: This manual describes what python-pyangbind is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/python-pyangbind/python-pyangbind.sgml.gz

Format: postscript
Files: /usr/share/doc/python-pyangbind/python-pyangbind.ps.gz

Format: text
Files: /usr/share/doc/python-pyangbind/python-pyangbind.text.gz

Format: HTML
Index: /usr/share/doc/python-pyangbind/html/index.html
Files: /usr/share/doc/python-pyangbind/html/*.html
