Document: python-bottle-cork
Title: Debian python-bottle-cork Manual
Author: <insert document author here>
Abstract: This manual describes what python-bottle-cork is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/python-bottle-cork/python-bottle-cork.sgml.gz

Format: postscript
Files: /usr/share/doc/python-bottle-cork/python-bottle-cork.ps.gz

Format: text
Files: /usr/share/doc/python-bottle-cork/python-bottle-cork.text.gz

Format: HTML
Index: /usr/share/doc/python-bottle-cork/html/index.html
Files: /usr/share/doc/python-bottle-cork/html/*.html
