Document: python-oslo.concurrency
Title: Debian python-oslo.concurrency Manual
Author: <insert document author here>
Abstract: This manual describes what python-oslo.concurrency is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/python-oslo.concurrency/python-oslo.concurrency.sgml.gz

Format: postscript
Files: /usr/share/doc/python-oslo.concurrency/python-oslo.concurrency.ps.gz

Format: text
Files: /usr/share/doc/python-oslo.concurrency/python-oslo.concurrency.text.gz

Format: HTML
Index: /usr/share/doc/python-oslo.concurrency/html/index.html
Files: /usr/share/doc/python-oslo.concurrency/html/*.html
