Document: geventhttpclient
Title: Debian geventhttpclient Manual
Author: <insert document author here>
Abstract: This manual describes what geventhttpclient is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/geventhttpclient/geventhttpclient.sgml.gz

Format: postscript
Files: /usr/share/doc/geventhttpclient/geventhttpclient.ps.gz

Format: text
Files: /usr/share/doc/geventhttpclient/geventhttpclient.text.gz

Format: HTML
Index: /usr/share/doc/geventhttpclient/html/index.html
Files: /usr/share/doc/geventhttpclient/html/*.html
