Document: python-pyang
Title: Debian python-pyang Manual
Author: <insert document author here>
Abstract: This manual describes what python-pyang is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/python-pyang/python-pyang.sgml.gz

Format: postscript
Files: /usr/share/doc/python-pyang/python-pyang.ps.gz

Format: text
Files: /usr/share/doc/python-pyang/python-pyang.text.gz

Format: HTML
Index: /usr/share/doc/python-pyang/html/index.html
Files: /usr/share/doc/python-pyang/html/*.html
